// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/bank/type/account.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceRequest) Reset() {
	*x = CurrentBalanceRequest{}
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceRequest) ProtoMessage() {}

func (x *CurrentBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceRequest.ProtoReflect.Descriptor instead.
func (*CurrentBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentBalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CurrrentBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber  string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	AccountName    string                 `protobuf:"bytes,2,opt,name=account_name,proto3" json:"account_name,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrentBalance float64                `protobuf:"fixed64,4,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	CreatedAt      *date.Date             `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt      *date.Date             `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CurrrentBalanceResponse) Reset() {
	*x = CurrrentBalanceResponse{}
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrrentBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrrentBalanceResponse) ProtoMessage() {}

func (x *CurrrentBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrrentBalanceResponse.ProtoReflect.Descriptor instead.
func (*CurrrentBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{1}
}

func (x *CurrrentBalanceResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CurrrentBalanceResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CurrrentBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CurrrentBalanceResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *CurrrentBalanceResponse) GetCreatedAt() *date.Date {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CurrrentBalanceResponse) GetUpdatedAt() *date.Date {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateRequest) Reset() {
	*x = ExchangeRateRequest{}
	mi := &file_proto_bank_type_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRequest) ProtoMessage() {}

func (x *ExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ExchangeRateResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency         string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency           string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	Rate                 float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	TransactionTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=transaction_timestamp,proto3" json:"transaction_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_proto_bank_type_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateResponse) GetTransactionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTimestamp
	}
	return nil
}

var File_proto_bank_type_account_proto protoreflect.FileDescriptor

const file_proto_bank_type_account_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/bank/type/account.proto\x12\x04bank\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproto/google/type/date.proto\"?\n" +
	"\x15CurrentBalanceRequest\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\"\x90\x02\n" +
	"\x17CurrrentBalanceResponse\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12\"\n" +
	"\faccount_name\x18\x02 \x01(\tR\faccount_name\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0fcurrent_balance\x18\x04 \x01(\x01R\x0ecurrentBalance\x121\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x11.google.type.DateR\n" +
	"created_at\x121\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x11.google.type.DateR\n" +
	"updated_at\"]\n" +
	"\x13ExchangeRateRequest\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\"\xc4\x01\n" +
	"\x14ExchangeRateResponse\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12P\n" +
	"\x15transaction_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x15transaction_timestampB5Z3github.com/seminhnva/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_account_proto_rawDescOnce sync.Once
	file_proto_bank_type_account_proto_rawDescData []byte
)

func file_proto_bank_type_account_proto_rawDescGZIP() []byte {
	file_proto_bank_type_account_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)))
	})
	return file_proto_bank_type_account_proto_rawDescData
}

var file_proto_bank_type_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_bank_type_account_proto_goTypes = []any{
	(*CurrentBalanceRequest)(nil),   // 0: bank.CurrentBalanceRequest
	(*CurrrentBalanceResponse)(nil), // 1: bank.CurrrentBalanceResponse
	(*ExchangeRateRequest)(nil),     // 2: bank.ExchangeRateRequest
	(*ExchangeRateResponse)(nil),    // 3: bank.ExchangeRateResponse
	(*date.Date)(nil),               // 4: google.type.Date
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_proto_bank_type_account_proto_depIdxs = []int32{
	4, // 0: bank.CurrrentBalanceResponse.created_at:type_name -> google.type.Date
	4, // 1: bank.CurrrentBalanceResponse.updated_at:type_name -> google.type.Date
	5, // 2: bank.ExchangeRateResponse.transaction_timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bank_type_account_proto_init() }
func file_proto_bank_type_account_proto_init() {
	if File_proto_bank_type_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_account_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_account_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_account_proto_msgTypes,
	}.Build()
	File_proto_bank_type_account_proto = out.File
	file_proto_bank_type_account_proto_goTypes = nil
	file_proto_bank_type_account_proto_depIdxs = nil
}
