// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/bank/type/transaction.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber   string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transaction_type,proto3" json:"transaction_type,omitempty"`
	Amount          string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       *datetime.DateTime     `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Notes           string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetTimestamp() *datetime.DateTime {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type TransactionSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber   string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	SumAmountIn     float64                `protobuf:"fixed64,2,opt,name=sum_amount_in,proto3" json:"sum_amount_in,omitempty"`
	SumAmountOut    float64                `protobuf:"fixed64,3,opt,name=sum_amount_out,proto3" json:"sum_amount_out,omitempty"`
	SumTotal        float64                `protobuf:"fixed64,4,opt,name=sum_total,proto3" json:"sum_total,omitempty"`
	TransactionDate *date.Date             `protobuf:"bytes,5,opt,name=transaction_date,proto3" json:"transaction_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSummary) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionSummary) GetSumAmountIn() float64 {
	if x != nil {
		return x.SumAmountIn
	}
	return 0
}

func (x *TransactionSummary) GetSumAmountOut() float64 {
	if x != nil {
		return x.SumAmountOut
	}
	return 0
}

func (x *TransactionSummary) GetSumTotal() float64 {
	if x != nil {
		return x.SumTotal
	}
	return 0
}

func (x *TransactionSummary) GetTransactionDate() *date.Date {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

var File_proto_bank_type_transaction_proto protoreflect.FileDescriptor

const file_proto_bank_type_transaction_proto_rawDesc = "" +
	"\n" +
	"!proto/bank/type/transaction.proto\x12\x04bank\x1a\x1cproto/google/type/date.proto\x1a proto/google/type/datetime.proto\"\xc4\x01\n" +
	"\vTransaction\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12*\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x10transaction_type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x123\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x15.google.type.DateTimeR\ttimestamp\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xe7\x01\n" +
	"\x12TransactionSummary\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12$\n" +
	"\rsum_amount_in\x18\x02 \x01(\x01R\rsum_amount_in\x12&\n" +
	"\x0esum_amount_out\x18\x03 \x01(\x01R\x0esum_amount_out\x12\x1c\n" +
	"\tsum_total\x18\x04 \x01(\x01R\tsum_total\x12=\n" +
	"\x10transaction_date\x18\x05 \x01(\v2\x11.google.type.DateR\x10transaction_dateB5Z3github.com/seminhnva/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_transaction_proto_rawDescOnce sync.Once
	file_proto_bank_type_transaction_proto_rawDescData []byte
)

func file_proto_bank_type_transaction_proto_rawDescGZIP() []byte {
	file_proto_bank_type_transaction_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)))
	})
	return file_proto_bank_type_transaction_proto_rawDescData
}

var file_proto_bank_type_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_transaction_proto_goTypes = []any{
	(*Transaction)(nil),        // 0: bank.Transaction
	(*TransactionSummary)(nil), // 1: bank.TransactionSummary
	(*datetime.DateTime)(nil),  // 2: google.type.DateTime
	(*date.Date)(nil),          // 3: google.type.Date
}
var file_proto_bank_type_transaction_proto_depIdxs = []int32{
	2, // 0: bank.Transaction.timestamp:type_name -> google.type.DateTime
	3, // 1: bank.TransactionSummary.transaction_date:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bank_type_transaction_proto_init() }
func file_proto_bank_type_transaction_proto_init() {
	if File_proto_bank_type_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_transaction_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_transaction_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_transaction_proto_msgTypes,
	}.Build()
	File_proto_bank_type_transaction_proto = out.File
	file_proto_bank_type_transaction_proto_goTypes = nil
	file_proto_bank_type_transaction_proto_depIdxs = nil
}
