syntax = "proto3";

package bank;

import "google/protobuf/timestamp.proto";

import "proto/google/type/date.proto";
option go_package = "github.com/seminhnva/my-grpc-proto/protogen/go/bank";

message CurrentBalanceRequest {
  string account_number = 1 [json_name = "account_number"];
}

message CurrrentBalanceResponse{
  string           account_number  = 1 [json_name ="account_number"];
  string           account_name    = 2 [json_name ="account_name"];
  string           currency        = 3;
  double           current_balance = 4;
  google.type.Date created_at      = 5 [json_name="created_at"];
  google.type.Date updated_at      = 6 [json_name="updated_at"];
}

message ExchangeRateRequest{
  string from_currency = 1 [json_name="from_currency"];
  string to_currency   = 2 [json_name = "to_currency"];
}

message ExchangeRateResponse{
  string from_currency         = 1 [json_name="from_currency"];
  string to_currency           = 2 [json_name = "to_currency"];
  double rate                  = 3;
  google.protobuf.Timestamp transaction_timestamp = 4 
  [json_name="transaction_timestamp"];

}