syntax = "proto3";

package bank;

import "proto/google/type/date.proto";
import "proto/google/type/datetime.proto";


message Transaction {
  string               account_number   = 1 [json_name ="account_number"];
  string               transaction_type = 2 [json_name ="transaction_type"];
  string               amount           = 3;
  google.type.DateTime timestamp        = 4;
  string               notes            = 5;
}
message TransactionSummary {
  string account_number = 1 [json_name = "account_number"];
  double sum_amount_in = 2 [json_name = "sum_amount_in"];
  double sum_amount_out = 3 [json_name = "sum_amount_out"];
  double sum_total = 4 [json_name = "sum_total"];
  google.type.Date transaction_date = 5 [json_name = "transaction_date"];
}