swagger: "2.0"
info:
  title: proto/hello/hello.proto
  version: version not set
tags:
  - name: HelloService
  - name: BankService
consumes:
  - application/json
produces:
  - application/json
paths:
  /bank.BankService/FetchExchangeRates:
    post:
      operationId: BankService_FetchExchangeRates
      responses:
        "200":
          description: A successful response.(streaming responses)
          schema:
            type: object
            properties:
              result:
                $ref: '#/definitions/bankExchangeRateResponse'
              error:
                $ref: '#/definitions/rpcStatus'
            title: Stream result of bankExchangeRateResponse
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/bankExchangeRateRequest'
      tags:
        - BankService
  /bank.BankService/GetCurrentBalance:
    post:
      operationId: BankService_GetCurrentBalance
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/bankCurrrentBalanceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/bankCurrentBalanceRequest'
      tags:
        - BankService
  /hello.HelloService/SayHello:
    post:
      operationId: HelloService_SayHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/helloHelloResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/helloHelloRequest'
      tags:
        - HelloService
  /hello.HelloService/SayHelloContinuous:
    post:
      operationId: HelloService_SayHelloContinuous
      responses:
        "200":
          description: A successful response.(streaming responses)
          schema:
            type: object
            properties:
              result:
                $ref: '#/definitions/helloHelloResponse'
              error:
                $ref: '#/definitions/rpcStatus'
            title: Stream result of helloHelloResponse
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          description: ' (streaming inputs)'
          in: body
          required: true
          schema:
            $ref: '#/definitions/helloHelloRequest'
      tags:
        - HelloService
  /hello.HelloService/SayHelloToEveryone:
    post:
      operationId: HelloService_SayHelloToEveryone
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/helloHelloResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          description: ' (streaming inputs)'
          in: body
          required: true
          schema:
            $ref: '#/definitions/helloHelloRequest'
      tags:
        - HelloService
  /hello.HelloService/SayManyHello:
    post:
      operationId: HelloService_SayManyHello
      responses:
        "200":
          description: A successful response.(streaming responses)
          schema:
            type: object
            properties:
              result:
                $ref: '#/definitions/helloHelloResponse'
              error:
                $ref: '#/definitions/rpcStatus'
            title: Stream result of helloHelloResponse
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/helloHelloRequest'
      tags:
        - HelloService
definitions:
  bankCurrentBalanceRequest:
    type: object
    properties:
      account_number:
        type: string
  bankCurrrentBalanceResponse:
    type: object
    properties:
      account_number:
        type: string
      account_name:
        type: string
      currency:
        type: string
      currentBalance:
        type: number
        format: double
      created_at:
        $ref: '#/definitions/typeDate'
      updated_at:
        $ref: '#/definitions/typeDate'
  bankExchangeRateRequest:
    type: object
    properties:
      from_currency:
        type: string
      to_currency:
        type: string
  bankExchangeRateResponse:
    type: object
    properties:
      from_currency:
        type: string
      to_currency:
        type: string
      rate:
        type: number
        format: double
      transaction_timestamp:
        type: string
        format: date-time
  helloHelloRequest:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
        format: int64
  helloHelloResponse:
    type: object
    properties:
      greet:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  typeDate:
    type: object
    properties:
      year:
        type: integer
        format: int32
        description: |-
          Year of the date. Must be from 1 to 9999, or 0 to specify a date without
          a year.
      month:
        type: integer
        format: int32
        description: |-
          Month of a year. Must be from 1 to 12, or 0 to specify a year without a
          month and day.
      day:
        type: integer
        format: int32
        description: |-
          Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
          to specify a year by itself or a year and month where the day isn't
          significant.
    description: |-
      * A full date, with non-zero year, month, and day values.
      * A month and day, with a zero year (for example, an anniversary).
      * A year on its own, with a zero month and a zero day.
      * A year and month, with a zero day (for example, a credit card expiration
        date).

      Related types:

      * [google.type.TimeOfDay][google.type.TimeOfDay]
      * [google.type.DateTime][google.type.DateTime]
      * [google.protobuf.Timestamp][google.protobuf.Timestamp]
    title: |-
      Represents a whole or partial calendar date, such as a birthday. The time of
      day and time zone are either specified elsewhere or are insignificant. The
      date is relative to the Gregorian Calendar. This can represent one of the
      following:
